### ISSUE TITLE
BUG: converting from version 2.x/3.x

### ISSUE THREAD

**Issue by bitbay** [DragonBones/Tools#2]
I tried to convert an animation exported from Flash using the DesignPanel v3.0.1 to the new v5.5 format, but it seems that one of the two is failing:
* **db2** while converting 2.3 to 5.5
* **dragonBones** v5.1.0 at importing/visualizing the data

I attach two images and the two skeletons with their textures/atlases.

This is how it is expected to look like:
![expected_result](https://user-images.githubusercontent.com/2558741/31878018-dfb6edf2-b7d8-11e7-9a13-188571c4b49f.png)
...and this is how it ends up
![issue](https://user-images.githubusercontent.com/2558741/31878050-f7e64f44-b7d8-11e7-801b-42f30e16733e.png)

This is [exported.zip](https://github.com/DragonBones/Tools/files/1406176/exported.zip) from DesignPanel 3.0.1, using the command
```$ db2 -t new -i ./exported -o ./converted```
i got to this skeleton [converted.zip](https://github.com/DragonBones/Tools/files/1406187/converted.zip)

**Comment by akdcl** [comment]
Hi, we will fixed the bug asap :)

**Comment by akdcl** [comment]
Hi, the bug has been fixed, you can upgrade the tools.

**Comment by mobiledevnetwizzy** [comment]
Thank You @akdcl, updating with ```npm install -g dragonbones-tools``` to @0.0.31 did it!

**Comment by mobiledevnetwizzy** [comment]
did this patch/fix landed in the master branch of the repo?

**Comment by akdcl** [comment]
@mobiledevnetwizzy Hi, the bug has been pushed to master branch, is it still has transform bug with 2.x to 5.x？

**Comment by mobiledevnetwizzy** [comment]
@akdcl aparently yes, but i'm not quite sure because of a clean clone build failing for dragonbones tools.
```
$ git clone https://github.com/DragonBones/Tools.git && cd Tools
Tools$ npm install
Tools$ npm 
Tools$ npm run build
> dragonbones-tools@0.0.32 build E:\tmp\dragonbones\Tools-clean
> tsc & dbp -t tools

"tsc" is not recognized as an internal or external command,
operable program or batch file.
"dbp" is not recognized as an internal or external command,
operable program or batch file.
```
Adding the following dependencies to `package.json`
```
"dependencies": {
     ...
     "@types/node": "^8.0.47",
     "typescript": "^2.6.1"
   }
```
i'm left with the `dbp -t tools` failing.

Cloning and building the [repo](https://github.com/bitbay/Tools/) of @bitbay the result is the same (bug present), but it may have to do with that repo and not the Tools itself.

**Comment by akdcl** [comment]
@mobiledevnetwizzy if you want to build the tools, you can run command like this:
```
npm install
npm install tsc --global
tsc
```
You can read the README.md to find how to build the dragonbones tools.

**Comment by mobiledevnetwizzy** [comment]
@akdcl with the `tsc` command it compiles perfectly and gives the correct result.
So it must me the `web-bundle` version of @bitbay that's missing something...
Thanks again!
