### ISSUE TITLE
BUG: FrameEvents off after converting from version 2.x/3.x to "new"

### ISSUE THREAD

**Issue by bitbay** [DragonBones/Tools#4]
I add an exported skeleton v2.3 i am converting with dragonbones-tools@0.0.32.
The old version has the event firing at the expected frame, and in the skeleton it looks like:
```
"frame": [
    {
        "duration": 59
    },
    {
        "duration": 41,
        "event": "event_label"
    }
],
```
as expected, the animation is 100 frames long, and at frame 60 i have a label "@event_label".
Now the updated skeleton is missing any duration data after conversion with `db2 -t new`, and looks like (again, only the interesting part):
```
"animation": [
    {
        "duration": 100,
        "name": "animation_label",
        "frame": [
            {},
            {
                "event": "event_label"
            }
        ]
    }
]
```
If i "correct" it manually adding the missing "duration" data, it works as expected:
```
"frame": [
    {
        "duration": 59 // adding this line does the job!
    },
    {
        "event": "event_label",
        "duration": 41  // not sure if this does anything...
    }
]
```
[frameevent.zip](https://github.com/DragonBones/Tools/files/1492300/frameevent.zip)

**Comment by bitbay** [comment]
...forgot to mention that what happens with the incorrect/buggy export is that the event fires right after playing the animation - although it only should 59 frames ahead.

**Comment by akdcl** [comment]
Hi, thanks for your example, the bug has been fixed :)
90c26c1bfec2c3a73ba4f0a020f9f241163a9441
