### ISSUE TITLE
2db -t new fails 

### ISSUE THREAD

**Issue by radu-m** [DragonBones/Tools#7]
Running the command `2db -t new` fails with the message `Unknown type: none` and I was unable to find any workaround to this. 
Conversely, `db2 -t new` on the same path prints `Convert complete` but there are no changes to the original file or any new files.

**Comment by akdcl** [comment]
Perhaps the command you need to execute is `2db -t spine`.

**Comment by akdcl** [comment]
Sorry, `2db -t new` is a typo.
